spring:
  datasource:
    url: jdbc:mysql://192.168.0.17:3306/tododb?useSSL=false&serverTimezone=Asia/Tokyo
    #url: jdbc:mysql://mysql84:3306/tododb?useSSL=false&serverTimezone=Asia/Tokyo
    username: yama
    password: yama
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/sql/**/*.xml
  type-aliases-package: com.example.backend.db.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  address: 0.0.0.0
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.mybatis: DEBUG
